image: "smblott/dcu-docker-gitlab-ci"

testA0:
  script:
    - "django-admin --version"
    - "echo ok checking submission for A0"
    - "echo running python django test"
    - "cd src/ca377; python3 manage.py test eatatdcu"
    - "echo finished A0 submission checks"
