# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-15 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='staff',
            field=models.CharField(default='', max_length=100),
        ),
    ]
