# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0002_restaurant_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='staff',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_staff_only',
            field=models.BooleanField(default=False),
        ),
    ]
