# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0003_auto_20181016_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_hours_wknd',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_open_wknd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours_wknd',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
